/run/initialize

/vis/open OGLSQt
/vis/drawVolume

/vis/viewer/set/style wireframe
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/hiddenEdge true
/vis/viewer/zoom 1.5

# Store particle trajectories
/tracking/storeTrajectory 1

# Create a trajectory model
/vis/modeling/trajectories/create/drawByCharge

# Add trajectories to the scene
/vis/scene/add/trajectories

# Keep trajectories after each event
/vis/scene/endOfEventAction accumulate

/vis/viewer/flush
